# Generated by Django 5.0.3 on 2024-03-28 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "environment_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectEnvironmentFeatureStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=20)),
                ("value", models.TextField(max_length=750)),
                ("tag", models.CharField(blank=True, max_length=20, null=True)),
                ("tag_color", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=750, null=True),
                ),
                ("enabled_by_default", models.BooleanField(default=False)),
                ("last_used", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Environment Feature Storage",
                "verbose_name_plural": "Project Environment Features Storage",
            },
        ),
        migrations.CreateModel(
            name="ProjectEnvironmentUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("features", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Project User",
                "verbose_name_plural": "Project User",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Administrator", "Organization Administrator"),
                    ("User", "User"),
                ],
                default="User",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrganizationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="organization_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="project_groups", to="switchkey.organizationgroup"
                    ),
                ),
                (
                    "team",
                    models.ManyToManyField(
                        null=True,
                        related_name="project_team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environments",
                    models.ManyToManyField(
                        related_name="project_environments",
                        to="switchkey.projectenvironment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Project",
                "verbose_name_plural": "Organization Projects",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="organization_members", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="organization_projects",
                        to="switchkey.organizationproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AddField(
            model_name="projectenvironment",
            name="default_features",
            field=models.ManyToManyField(
                related_name="environment_default_features",
                to="switchkey.projectenvironmentfeaturestorage",
            ),
        ),
        migrations.AddField(
            model_name="projectenvironment",
            name="users",
            field=models.ManyToManyField(
                related_name="environment_users", to="switchkey.projectenvironmentuser"
            ),
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("IPhone", "iPhone"), ("Android", "Android")],
                        default="Android",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "User Device",
                "verbose_name_plural": "User Device",
                "unique_together": {("device_type", "version")},
            },
        ),
        migrations.AddField(
            model_name="projectenvironmentuser",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_device",
                to="switchkey.userdevice",
            ),
        ),
        migrations.DeleteModel(
            name="KeyValueStorage",
        ),
    ]
