# Generated by Django 5.0.3 on 2024-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0003_alter_organizationproject_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="organization_projects",
                to="switchkey.organizationproject",
            ),
        ),
    ]
