# Generated by Django 5.0.3 on 2024-03-28 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0004_alter_organization_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="organization_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
