# Generated by Django 5.0.3 on 2024-03-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0007_alter_organizationproject_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationproject",
            name="environments",
        ),
        migrations.RemoveField(
            model_name="organizationproject",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="organizationproject",
            name="team",
        ),
        migrations.AddField(
            model_name="projectenvironment",
            name="project",
            field=models.ManyToManyField(
                blank=True,
                related_name="environment_project",
                to="switchkey.organizationproject",
            ),
        ),
    ]
