# Generated by Django 5.0.3 on 2024-03-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0009_remove_organization_projects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectenvironment",
            name="default_features",
        ),
        migrations.AddField(
            model_name="projectenvironmentfeaturestorage",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment_keys",
                to="switchkey.projectenvironment",
            ),
        ),
        migrations.AlterField(
            model_name="projectenvironment",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="environment_users",
                to="switchkey.projectenvironmentuser",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectenvironmentfeaturestorage",
            unique_together={("environment", "key")},
        ),
    ]
