# Generated by Django 5.0.3 on 2024-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0010_remove_projectenvironment_default_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectenvironmentfeaturestorage",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
