# Generated by Django 5.0.3 on 2024-03-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0011_projectenvironmentfeaturestorage_is_default"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectEnvironmentFeatureStorage",
            new_name="FeatureStorage",
        ),
    ]
