# Generated by Django 5.0.3 on 2024-03-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0016_organization_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationGroup",
            new_name="OrganizationProjectGroup",
        ),
    ]
