# Generated by Django 5.0.3 on 2024-03-29 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0017_rename_organizationgroup_organizationprojectgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprojectgroup",
            name="project",
        ),
        migrations.AddField(
            model_name="organizationprojectgroup",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_groups",
                to="switchkey.organizationproject",
            ),
            preserve_default=False,
        ),
    ]
