# Generated by Django 5.0.3 on 2024-03-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0018_remove_organizationprojectgroup_project_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationprojectgroup",
            options={
                "verbose_name": "Organization Project Group",
                "verbose_name_plural": "Organization Project Groups",
            },
        ),
        migrations.AlterUniqueTogether(
            name="organizationprojectgroup",
            unique_together={("name", "project")},
        ),
    ]
