# Generated by Django 5.0.3 on 2024-03-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0019_alter_organizationprojectgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organization",
            unique_together={("name", "owner")},
        ),
    ]
