# Generated by Django 5.0.3 on 2024-03-31 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0021_alter_organization_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FeatureStorage",
            new_name="EnvironmentFeature",
        ),
    ]
