# Generated by Django 5.0.3 on 2024-03-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0023_alter_environmentfeature_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Administrator", "Organization Administrator"),
                    ("User", "User"),
                ],
                default="Administrator",
                max_length=20,
            ),
        ),
    ]
