# Generated by Django 5.0.3 on 2024-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkey", "0024_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Administrator", "administrator"), ("User", "user")],
                default="Administrator",
                max_length=20,
            ),
        ),
    ]
