# Generated by Django 5.0.3 on 2024-04-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("switchkeys", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectenvironment",
            options={
                "verbose_name": "Organization Project Group",
                "verbose_name_plural": "Organization Project Groups",
            },
        ),
        migrations.AlterUniqueTogether(
            name="projectenvironment",
            unique_together={("name", "project")},
        ),
    ]
