# Generated by Django 5.0.3 on 2024-04-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("switchkeys", "0002_alter_projectenvironment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectenvironment",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="projectenvironment",
            unique_together=set(),
        ),
    ]
