# Generated by Django 5.0.3 on 2024-04-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "switchkeys",
            "0004_rename_enabled_by_default_environmentfeature_is_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="environmentfeature",
            unique_together={
                ("environment", "name", "value", "is_enabled", "is_default")
            },
        ),
    ]
