# Generated by Django 5.0.3 on 2024-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkeys", "0005_alter_environmentfeature_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="environmentfeature",
            unique_together={("environment", "name", "value")},
        ),
        migrations.AlterField(
            model_name="environmentfeature",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name="environmentfeature",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="environmentfeature",
            name="is_enabled",
        ),
    ]
