# Generated by Django 5.0.3 on 2024-04-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkeys", "0006_alter_environmentfeature_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchKeysFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("value", models.TextField(max_length=5000, verbose_name="Value")),
                (
                    "initial_value",
                    models.TextField(max_length=5000, verbose_name="Initial Value"),
                ),
                ("is_default", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "SwitchKeys Feature",
                "verbose_name_plural": "SwitchKeys Features",
            },
        ),
        migrations.AlterUniqueTogether(
            name="environmentfeature",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="projectenvironmentuser",
            name="features",
        ),
        migrations.AlterField(
            model_name="environmentfeature",
            name="environment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_environment",
                to="switchkeys.projectenvironment",
                verbose_name="Environment",
            ),
        ),
        migrations.AddField(
            model_name="environmentfeature",
            name="features",
            field=models.ManyToManyField(
                related_name="environment_default_features",
                to="switchkeys.switchkeysfeature",
                verbose_name="Features",
            ),
        ),
        migrations.RemoveField(
            model_name="environmentfeature",
            name="name",
        ),
        migrations.RemoveField(
            model_name="environmentfeature",
            name="value",
        ),
        migrations.CreateModel(
            name="UserFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "feature_value",
                    models.TextField(
                        help_text="The value of the feature associated with the user.",
                        max_length=5000,
                        verbose_name="Value",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_feature",
                        to="switchkeys.switchkeysfeature",
                        verbose_name="Feature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_feature",
                        to="switchkeys.projectenvironmentuser",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feature",
                "verbose_name_plural": "User Features",
                "unique_together": {("user", "feature")},
            },
        ),
    ]
