# Generated by Django 5.0.3 on 2024-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switchkeys", "0007_switchkeysfeature_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectenvironmentuser",
            options={
                "verbose_name": "Environment User",
                "verbose_name_plural": "Environment Users",
            },
        ),
        migrations.AddField(
            model_name="projectenvironmentuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
